### ISSUE TITLE
onFocus event doesn't fire

### ISSUE THREAD

**Issue by ivan-rodriguez-ag** [spring-media/react-shadow-dom-retarget-events#18]
Hi,

I am trying to make a micro-frontend app into a web component into shadow-dom to avoid conflict bwtween both pages. I have use this package but i discovered that onFocus event is not fired, i tryed to make it manually but i didn't get to make it work.

Do you know why it is not working? 
Any idea on how i could fix that (i could make PR)?

**Comment by newying61** [comment]
Which browser are you using? Is it support Web Component natively?

Try to render the app into shadowRoot directly, instead of creating a div wrapper.
```
ReactDOM.render(<App />, this.shadowRoot)
```
This should work. And you should not need this lib.

The reason is onFocus is not bubbling. The SyntheticEvent System in React is using Capture phase for focus / blur events.
But this lib is using an event listener in shadowRoot in bubble phase.
That's why it's not triggering, I think.

**Comment by ivan-rodriguez-ag** [comment]
I was using shadow-dom because i needed to inject in other app without iframe. Now i don't need shadow-dom because i took time to change the Styles yo work good.
